# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2024 The NeuralVirtualizer Authors
import os
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), ".."))
# # Show only WARNING and above logs
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import argparse
import fileinput
import gc
import glob
import json
import random
import tensorflow as tf
import tempfile
import shutil
import base64
import struct
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.backends import default_backend

from graph_virtualizer import graph_virtualization_process, virtualize_graph
from ops_virtualizer import op_types_virtualization_process, encrypt_shape, virtualize_op_types
from params_virtualizer import params_virtualization_process, virtualize_params, generate_params_file
from utils.utils import convert_dtype_for_json, extract_all_op_types, extract_all_parameters, extract_graph, apply_random_index_mapping


def load_crypto_params(binary_path='keys_and_offsets.bin'):
    """
    Load plaintext cryptographic parameters from binary file.

    This function reads the 168-byte binary file generated by scripts/generate_keys.py
    and returns all parameters needed for virtualization (modulus values, AES keys, nonce bases).

    Args:
        binary_path: Path to the binary file (default: keys_and_offsets.bin)

    Returns:
        dict: Contains op_modulus, conn_modulus, aes_keys, and nonce_bases
              Structure: {
                  'op_modulus': uint32,
                  'conn_modulus': uint32,
                  'aes_keys': {'op': bytes32, 'param': bytes32, 'graph': bytes32, 'shape': bytes32},
                  'nonce_bases': {'op': bytes8, 'param': bytes8, 'graph': bytes8, 'shape': bytes8}
              }
    """
    if not os.path.exists(binary_path):
        print(f"ERROR: {binary_path} not found!")
        print("Please run scripts/generate_keys.py first to generate keys.")
        sys.exit(1)

    file_size = os.path.getsize(binary_path)
    if file_size != 168:
        print(f"ERROR: {binary_path} has invalid size: {file_size} bytes (expected 168)")
        sys.exit(1)

    domains = ['op', 'param', 'graph', 'shape']
    crypto_params = {
        'aes_keys': {},
        'nonce_bases': {}
    }

    with open(binary_path, 'rb') as f:
        # Read modulus values (8 bytes)
        modulus_data = f.read(8)
        crypto_params['op_modulus'], crypto_params['conn_modulus'] = struct.unpack('<II', modulus_data)

        # Read 4 domains × (32-byte plaintext key + 8-byte nonce)
        for domain in domains:
            crypto_params['aes_keys'][domain] = f.read(32)  # Plaintext key
            crypto_params['nonce_bases'][domain] = f.read(8)  # Nonce base

    print(f"✓ Loaded crypto parameters from {binary_path}")
    print(f"  - op_modulus={crypto_params['op_modulus']}, conn_modulus={crypto_params['conn_modulus']}")

    return crypto_params


def encrypt_metadata(metadata, crypto_params):
    """
    Encrypt model metadata (input_shapes, input_dtypes, input_shape_signatures, input_ops, output_ops).

    Uses shape domain key and fixed nonce (shape_nonce_base + 0x00*8) for encryption.
    The entire metadata JSON is serialized and encrypted as a single blob.

    Args:
        metadata: Dictionary containing metadata fields
        crypto_params: Cryptographic parameters loaded from load_crypto_params()

    Returns:
        str: Base64-encoded encrypted metadata
    """
    # Serialize metadata as deterministic JSON
    metadata_json = json.dumps(metadata, separators=(',', ':'), sort_keys=True)

    # Construct 16-byte nonce: shape_nonce_base (8 bytes) + counter (8 bytes of 0x00)
    nonce = crypto_params['nonce_bases']['shape'] + b'\x00' * 8

    # Create AES-256-CTR cipher using plaintext shape key
    cipher = Cipher(
        algorithms.AES(crypto_params['aes_keys']['shape']),
        modes.CTR(nonce),
        backend=default_backend()
    )
    encryptor = cipher.encryptor()

    # Encrypt metadata JSON
    plaintext = metadata_json.encode('utf-8')
    ciphertext = encryptor.update(plaintext) + encryptor.finalize()

    # Return Base64-encoded ciphertext
    return base64.b64encode(ciphertext).decode('ascii')


# Simplify the model JSON file by removing the buffers field
def reduce_size_json(json_file):
    # Use a temporary file for streaming to avoid reading the entire file at once
    temp_file = json_file + '.tmp'
    try:
        with open(json_file, 'r', encoding='utf-8') as input_file, \
            open(temp_file, 'w', encoding='utf-8') as output_file:
            keep_sign = True
            line_count = 0
            # Process line by line to avoid loading the entire file into memory
            for line in input_file:
                line_count += 1
                # Print progress every 10000 lines
                if line_count % 10000 == 0:
                    print(f"Processing JSON file progress: {line_count} lines")
                if 'buffers:' in line:
                    keep_sign = False
                    output_file.write('}\n')
                    break  # Stop immediately after finding buffers without further processing
                if keep_sign:
                    output_file.write(line)
        # Atomically replace the original file
        shutil.move(temp_file, json_file)
        print(f"JSON file simplification completed, processed {line_count} lines")
    except Exception as e:
        # Clean up temporary files
        if os.path.exists(temp_file):
            os.remove(temp_file)
        raise e

# Summarize virtualization information and generate a JSON file
# Consider further shuffling of layer ordering to disrupt sequential relationships
def generate_virtualization_file(v_op_types, v_params_info, v_graph, model_name, metadata, crypto_params):
    """
    Generate virtualization JSON file with encrypted metadata.

    Args:
        v_op_types: Virtualized operator types
        v_params_info: Virtualized parameters info
        v_graph: Virtualized graph connections
        model_name: Model name for output filename
        metadata: Dictionary with input_shapes, input_dtypes, input_shape_signatures, input_ops, output_ops
        crypto_params: Cryptographic parameters
    """
    # Encrypt metadata
    encrypted_metadata = encrypt_metadata(metadata, crypto_params)

    for op in v_op_types:
        # Initialize parameter-related fields (Base64-encoded encrypted data)
        op['v_position_data'] = []  # List of Base64-encoded encrypted position data
        op['v_shape'] = []  # List of Base64-encoded encrypted shape data
        # If graph input slot info exists ensure it is written
        if 'graph_input_slots' not in op:
            op['graph_input_slots'] = []
        # Add forward connection information
        for graph in v_graph:
            if graph['index'] == op['index']:
                op['v_forward_connections'] = graph['v_forward_connections']
                op['forward_branches'] = graph['forward_branches']
                break
        # Collect all parameter information for this operator
        shape_idx = 0  # Counter for shape encryption nonce
        for params in v_params_info:
            if params['op_index'] == op['index']:
                # Append encrypted position data (Base64 string)
                op['v_position_data'].append(params['v_position_data'])
                # Map dtype string to compact code
                # Robust dtype mapping: map all integer families to INT32 code (2)
                dtype_name = params.get('dtype', 'float32')
                d = str(dtype_name).lower() if dtype_name is not None else 'float32'
                if d in ('bool', 'boolean'):
                    dtype_code = 3  # BOOL
                elif d.startswith('int') or d.startswith('uint'):
                    # Treat all integer types as INT32 domain for parser typing
                    dtype_code = 2  # INT32
                elif d in ('float32', 'float', 'float16', 'float64', 'double'):
                    dtype_code = 1  # FLOAT32 family
                else:
                    # Default to float32 to be safe for unknowns
                    dtype_code = 1
                # Determine param slot (fallback -1)
                param_slot = params.get('input_slot', -1)
                # Encrypt shape with extended header and append (Base64 string)
                encrypted_shape = encrypt_shape(params['shape'], op['index'], shape_idx, crypto_params, dtype_code, param_slot)
                op['v_shape'].append(encrypted_shape)
                shape_idx += 1

    # Shuffle the operator array to break the original topology order
    # This is safe because all encryption uses semantic identifiers (op['index']) rather than array positions
    random.shuffle(v_op_types)

    # Build output structure with encrypted metadata
    output_data = {
        'encrypted_metadata': encrypted_metadata,
        'operators': v_op_types
    }

    serializable_info = convert_dtype_for_json(output_data)
    output_filename = f'{model_name}_v_infos.json'
    with open(output_filename, 'w', encoding='utf-8') as f:
        json.dump(serializable_info, f, indent=2, ensure_ascii=False)
    print(f"Virtualization information saved: {output_filename}")


# Command line argument parsing
parser = argparse.ArgumentParser()
parser.add_argument('--model_name', type=str, default='fruit', help='name of the model')
opt = parser.parse_args()

# Load model
model_path = 'tflite_model/'
model_name = opt.model_name + '.tflite'
print(f"Loading model underway: {model_name}")
interpreter = tf.lite.Interpreter(
    os.path.join(model_path, model_name)
)
interpreter.allocate_tensors()
print("Model loading completed")

# Parse the TFLite model into a JSON object
print("Start converting the TFLite model to JSON...")
os.system('flatc -t schema.fbs -- %s' % os.path.join(model_path, model_name))

print("Start simplifying the JSON file...")
reduce_size_json(os.path.splitext(model_name)[0] + '.json')

print("Fix JSON formatting...")
os.system('jsonrepair %s.json --overwrite' % os.path.splitext(model_name)[0])

# Memory-optimized JSON loading
print("Start loading the JSON file into memory...")
json_file_path = '%s.json' % os.path.splitext(model_name)[0]

# Check file size
file_size = os.path.getsize(json_file_path)
print(f"JSON file size: {file_size / (1024*1024):.2f} MB")

try:
    with open(json_file_path, 'r', encoding='utf-8') as f:
        model_json_f = f.read()
    print("Start parsing JSON...")
    model_json = json.loads(model_json_f)
    # Immediately release the original string memory
    del model_json_f
    gc.collect()
    print("JSON loading completed")
except Exception as e:
    print(f"JSON loading failed: {e}")
    raise

# Preprocessing fix placeholder issues in operator_codes
print("Start preprocessing operator_codes...")
from utils.utils import op_type_mapping
# Build a reverse mapping from operator names to codes
op_name_to_code = {v: k for k, v in op_type_mapping.items()}
fixed_count = 0
if 'operator_codes' in model_json:
    for opcode in model_json['operator_codes']:
        # Check for cases where deprecated_builtin_code equals 127 placeholder
        if opcode.get('deprecated_builtin_code') == 127:
            builtin_code_name = opcode.get('builtin_code', '')
            # Look up the correct code for the operator name in the mapping table
            if builtin_code_name in op_name_to_code:
                correct_code = op_name_to_code[builtin_code_name]
                opcode['deprecated_builtin_code'] = correct_code
                fixed_count += 1
                print(f"Fix placeholders: {builtin_code_name} deprecated_builtin_code: 127 -> {correct_code}")
            else:
                print(f"Warning: no mapping found for operator {builtin_code_name}, keeping original value 127")
print(f"Preprocessing completed, fixed {fixed_count} placeholder operators in total")

# Load cryptographic parameters from keys_and_offsets.bin
print("Loading cryptographic parameters...")
crypto_params = load_crypto_params('keys_and_offsets.bin')
print("Cryptographic parameters loaded successfully")

# Extract all information before virtualization
print("Extracting operator types...")
all_op_types, input_ops_index, output_ops_index, options_stats = extract_all_op_types(interpreter, model_json)
print(f"Extracted {len(all_op_types)} operators")

print("Extracting parameters...")
all_params, params_info = extract_all_parameters(interpreter, model_json)
print(f"Extracted {len(params_info)} parameters")

print("Extracting computation graph...")
graph = extract_graph(model_json)
print(f"Extracted {len(graph)} graph nodes")

# Apply random index mapping to break sequential patterns
print("Applying random index mapping...")
all_op_types, input_ops_index, output_ops_index, params_info, graph = \
    apply_random_index_mapping(all_op_types, input_ops_index, output_ops_index, params_info, graph)
print(f"Index mapping applied: {len(all_op_types)} operators remapped")

# Dynamic modulus detection
num_ops = len(all_op_types)
max_possible_index = num_ops * 10  # Random mapping range (apply_random_index_mapping uses 10x multiplier)
conn_modulus = crypto_params['conn_modulus']

if max_possible_index >= conn_modulus:
    print("=" * 70)
    print("ERROR: Connection modulus too small!")
    print(f"  - Model has {num_ops} operators")
    print(f"  - Max possible index after random mapping: {max_possible_index}")
    print(f"  - Current conn_modulus: {conn_modulus}")
    print("=" * 70)
    print("SOLUTION: Increase conn_modulus in scripts/generate_keys.py")
    sys.exit(1)

modulus_utilization = (max_possible_index / conn_modulus) * 100
if modulus_utilization > 80:
    print("=" * 70)
    print(f"WARNING: High modulus utilization ({modulus_utilization:.1f}%)")
    print(f"  - Model has {num_ops} operators")
    print(f"  - Max possible index: {max_possible_index}")
    print(f"  - conn_modulus: {conn_modulus}")
    print("  - Consider increasing conn_modulus for larger models")
    print("=" * 70)

gc.collect()  # Force garbage collection

# Layer type virtualization
print("Start layer type virtualization...")
v_op_types = virtualize_op_types(all_op_types, input_ops_index, output_ops_index, options_stats, crypto_params)
print(f"Layer type virtualization completed, processed {len(v_op_types)} operators in total")
gc.collect()  # Force garbage collection

# Parameter virtualization
print("Start parameter virtualization...")
total_size = generate_params_file(all_params, params_info, opt.model_name)
# Cover all operators to ensure Phase 3 dummy completion for ops with zero real params
all_op_indices = {op['index'] for op in v_op_types}
v_params_info = virtualize_params(params_info, total_size, crypto_params, all_op_indices)
print(f"Parameter virtualization completed, processed {len(v_params_info)} parameters in total")
gc.collect()  # Force garbage collection

# Computation graph virtualization
print("Start computation graph virtualization...")
v_graph = virtualize_graph(graph, crypto_params)
print(f"Computation graph virtualization completed, processed {len(v_graph)} nodes in total")
gc.collect()  # Force garbage collection

# JSON file generation
print("Start generating the virtualization information file...")

# Prepare metadata for encryption
# Apply modular arithmetic virtualization to input_ops and output_ops
v_input_ops = []
for real_input_op in input_ops_index:
    r = random.randint(1, 10000)
    v_input_op = r * crypto_params['conn_modulus'] + real_input_op
    v_input_ops.append(v_input_op)

v_output_ops = []
for real_output_op in output_ops_index:
    r = random.randint(1, 10000)
    v_output_op = r * crypto_params['conn_modulus'] + real_output_op
    v_output_ops.append(v_output_op)

metadata = {
    'input_shapes': [],
    'input_dtypes': [],
    'input_shape_signatures': [],
    'input_ops': v_input_ops,  # Virtualized using modular arithmetic
    'output_ops': v_output_ops  # Virtualized using modular arithmetic
}

# Extract input shapes, dtypes, and shape_signatures from interpreter
input_details = interpreter.get_input_details()
for input_detail in input_details:
    shape = input_detail['shape']
    dtype = input_detail['dtype']

    # Process shape (preserve dimensions including dynamic shapes)
    processed_shape = [int(dim) for dim in shape]
    metadata['input_shapes'].append(processed_shape)

    # Process dtype
    dtype_name = getattr(dtype, 'name', getattr(dtype, '__name__', str(dtype)))
    metadata['input_dtypes'].append(dtype_name)

# Extract input_shape_signatures from model JSON
try:
    subgraph = model_json['subgraphs'][0]
    tensors = subgraph.get('tensors', [])
    for tid in subgraph.get('inputs', []):
        tensor = tensors[tid]
        sig = tensor.get('shape_signature', tensor.get('shape', []))
        metadata['input_shape_signatures'].append(sig)
except Exception:
    # Fallback: use shape if shape_signature is missing
    for input_detail in input_details:
        metadata['input_shape_signatures'].append(list(input_detail['shape']))

generate_virtualization_file(v_op_types, v_params_info, v_graph, opt.model_name, metadata, crypto_params)
print("Virtualization information file generation completed!")

# Dynamically write test data, model filenames and input shapes
input_details = interpreter.get_input_details()

# Generate one line of code for input_shapes and input_dtypes
shapes_list = []
dtypes_list = []
for input_detail in input_details:
    shape = input_detail['shape']
    dtype = input_detail['dtype']
    # Preserve dynamic shapes
    processed_shape = []
    for dim in shape:
        processed_shape.append(int(dim))  # Directly preserve the original dimensions
    shapes_list.append(str(processed_shape))
    # Collect data types
    dtype_name = getattr(dtype, 'name', getattr(dtype, '__name__', str(dtype)))
    dtypes_list.append(f"'{dtype_name}'")

shapes_code = '[' + ', '.join(shapes_list) + ']'
dtypes_code = '[' + ', '.join(dtypes_list) + ']'

# Delete the JSON files generated by flatc
directory = './'
files = glob.glob(os.path.join(directory, '*'))
for file in files:
    filename = os.path.basename(file)
    if filename == os.path.splitext(model_name)[0] + '.json':
        os.remove(file)
        print(f"Deleted file: {file}")

# Clean up memory
del interpreter
if 'model_json' in locals():
    del model_json
gc.collect()
print("\n=== Virtualization completed ===")
